services:
  db:
    image: postgres:15-alpine
    container_name: postgres-local-new
    environment:
      POSTGRES_DB: Valet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

volumes:
  db-data:
